<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HealthNote.Application/HealthNote.Application.csproj" />
    <ProjectReference Include="../HealthNote.Domain/HealthNote.Domain.csproj" />
    <ProjectReference Include="../HealthNote.Infrastructure/HealthNote.Infrastructure.csproj" />
  </ItemGroup>
</Project>
